_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.7.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 16
decay_rate:
    value: 0.0001
epoch:
    value: 1000
gpu:
    value: "0"
learning_rate:
    value: 0.002
log_dir:
    value: null
model:
    value: pointnet2_cls_msg_DeYun
normal:
    value: false
num_point:
    value: 1024
optimizer:
    value: Adam
